[package]
name = "stabilize"
version = "0.1.0"
authors = ["Freddie Brown <fred@noser.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2.4", features = ["full"] }
futures = "0.3.5"
tokio-util = { version = "0.3.1", features = ["full"] }
http = "0.2.1"
httparse = "1.3.4"
bytes = "0.5.5"
tokio-test = "0.2"
